services:
  trial_docker:
    ports:
      - 5000:5000
    build:
      context: .
      dockerfile: Dockerfile
    image: trial_docker:v1
    working_dir: /app
    command: bash -c "python flask_app.py"
